services:
  - type: web
    name: hopper-api
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildContext: backend
    envVars:
      - key: DB_URI
        sync: false  # Uses Render's dashboard value (NOT hardcoded)

  - type: web
    name: hopper-ui
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    buildContext: frontend
