services:
  - type: web
    name: hopper-fullstack
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: DB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_VERSION
        value: 18
