services:
  - type: web
    name: hopper-api
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    envVars:
  - key: DB_URI
    value: {{ env "DB_URI" }}


  - type: web
    name: hopper-ui
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    buildCommand: ""
