services:
  - type: web
    name: hopper-api
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildContext: backend
    startCommand: node server.js
    envVars:
      - key: DB_URI
        sync: false
  - type: web
    name: hopper-ui
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    buildContext: frontend
