services:
  - type: web
    name: hopper-api
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    envVars:
      - key: DB_URI
        value: mongodb+srv://Mbarhou:comp313@hr-enterprise.lx2ox.mongodb.net/HR_db?retryWrites=true&w=majority&appName=HR-Enterprise

  - type: web
    name: hopper-ui
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    buildCommand: ""
